name: Release-Notes-Preview

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: Github token
        required: true
permissions:
  contents: read
  packages: read
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - run: |
          git fetch --prune --unshallow --tags
      - uses: snyk/release-notes-preview@v1.6.2
        with:
          releaseBranch: main
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
